version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"