version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: fruits
      POSTGRES_PASSWORD: fruits
      POSTGRES_DB: fruits
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5431:5432"